### ISSUE TITLE
Error after running multiple times.

### ISSUE THREAD

**Issue by Almancat10** [thebotsmith/ebay-views-gen#2]
I run the bot once and it works, then the second time I run the bot it always gives me this error and I have to restart it: 

Traceback (most recent call last):
  File "/Users/myself/Downloads/ebay-views-gen-master/discord-views-bot.py", line 56, in <module>
    client.run(TOKEN)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/discord/client.py", line 519, in run
    self.loop.run_until_complete(self.start(*args, **kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/base_events.py", line 364, in run_until_complete
    self._check_closed()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/base_events.py", line 334, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

**Comment by alpha1337** [comment]
I also have this issue
